# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('length', models.IntegerField()),
            ],
            options={
                'ordering': ['railroad', 'type', 'number'],
                'db_table': 'car',
            },
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'cartype',
            },
        ),
        migrations.CreateModel(
            name='Coupler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'coupler',
            },
        ),
        migrations.CreateModel(
            name='Locomotive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('length', models.IntegerField()),
                ('axles', models.IntegerField()),
                ('coupler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Coupler')),
            ],
            options={
                'ordering': ['railroad', 'number'],
                'db_table': 'locomotive',
            },
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'make',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'manufacturer',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Make')),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'model',
            },
        ),
        migrations.CreateModel(
            name='Railroad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'railroad',
            },
        ),
        migrations.CreateModel(
            name='StockType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'stocktype',
            },
        ),
        migrations.AddField(
            model_name='locomotive',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Make'),
        ),
        migrations.AddField(
            model_name='locomotive',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Manufacturer'),
        ),
        migrations.AddField(
            model_name='locomotive',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Model'),
        ),
        migrations.AddField(
            model_name='locomotive',
            name='railroad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Railroad'),
        ),
        migrations.AddField(
            model_name='locomotive',
            name='stocktype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.StockType'),
        ),
        migrations.AddField(
            model_name='coupler',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Manufacturer'),
        ),
        migrations.AddField(
            model_name='cartype',
            name='stocktype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.StockType'),
        ),
        migrations.AddField(
            model_name='car',
            name='coupler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Coupler'),
        ),
        migrations.AddField(
            model_name='car',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Manufacturer'),
        ),
        migrations.AddField(
            model_name='car',
            name='railroad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Railroad'),
        ),
        migrations.AddField(
            model_name='car',
            name='stocktype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.StockType'),
        ),
        migrations.AddField(
            model_name='car',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.CarType'),
        ),
    ]
