# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 03:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20170117_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartype',
            name='stocktype',
        ),
    ]
