# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 00:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='locomotive',
            name='power',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.Power'),
            preserve_default=False,
        ),
    ]
