# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_locomotive_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='locomotive',
            name='address',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='length',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='locomotive',
            name='length',
            field=models.IntegerField(null=True),
        ),
    ]
