# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 01:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20170119_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='coupler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Coupler'),
        ),
        migrations.AlterField(
            model_name='locomotive',
            name='address',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='locomotive',
            name='axles',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='locomotive',
            name='coupler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Coupler'),
        ),
    ]
