# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20170119_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='modelnumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='locomotive',
            name='modelnumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
