# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20170121_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='livery',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='locomotive',
            name='livery',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
