# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20170123_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='couplerTuned',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='locomotive',
            name='couplerTuned',
            field=models.NullBooleanField(),
        ),
    ]
