# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20170129_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locomotive',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
