# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 01:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_auto_20170302_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='WheelMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'wheelmaterial',
            },
        ),
        migrations.CreateModel(
            name='WheelSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.WheelMaterial')),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'wheelset',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='wheelset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.WheelSet'),
        ),
    ]
