# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 01:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_auto_20170306_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheelset',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Manufacturer'),
        ),
    ]
