# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_wheelset_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='locomotive',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
